"""add_subscription_title_to_admin

Revision ID: 2c7e7160c0d5
Revises: 2b231de97dc3
Create Date: 2025-12-31 20:48:04.827655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c7e7160c0d5'
down_revision = '2b231de97dc3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('subscription_title', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'subscription_title')
    # ### end Alembic commands ###
