"""add_announce_fields_to_admin

Revision ID: 67fc0a6b8aa2
Revises: 2c7e7160c0d5
Create Date: 2025-12-31 20:56:56.784593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67fc0a6b8aa2'
down_revision = '2c7e7160c0d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('announce', sa.String(1024), nullable=True))
    op.add_column('admins', sa.Column('announce_url', sa.String(1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'announce_url')
    op.drop_column('admins', 'announce')
    # ### end Alembic commands ###
